[versions]
androidCompileSdk = "34"
androidTargetSdk = "34"
kotlin = "1.9.23"
coil = "3.0.0-alpha01"
compose-multiplatform = "1.6.2"
coroutines = "1.8.1"
agp = "8.4.1"
maven-publish = "0.28.0"
ktor = "2.3.11"

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network = { module = "io.coil-kt.coil3:coil-network", version.ref = "coil" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
mavenpublish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
